# Generated by Django 5.2.1 on 2025-05-28 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_formationreview_alter_formation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation', to='formations.formationcategory', verbose_name='Catégorie'),
        ),
    ]
