# Generated by Django 5.2.1 on 2025-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
    ]
