# Generated by Django 5.2.1 on 2025-05-24 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_updated_at_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
