# Generated by Django 5.2.1 on 2025-05-25 18:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Vue d'annonce",
                'verbose_name_plural': "Vues d'annonce",
            },
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('-created_at',), 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='advertisementimage',
            options={'ordering': ('-is_main', 'created_at'), 'verbose_name': "Image d'annonce", 'verbose_name_plural': "Images d'annonce"},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-created_at',), 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='updated',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='advertisementimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'ajout"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='publicites.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='advertisementimage',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publicites.advertisement', verbose_name='Annonce'),
        ),
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=models.ImageField(upload_to='publicites/images/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='publicites.advertisement', verbose_name='Annonce'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['-created_at'], name='publicites__created_a624a9_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status'], name='publicites__status_4de47e_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['is_premium'], name='publicites__is_prem_23d399_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['category'], name='publicites__categor_5effc3_idx'),
        ),
        migrations.AddField(
            model_name='advertisementview',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='publicites.advertisement'),
        ),
        migrations.AddField(
            model_name='advertisementview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisement_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='advertisementview',
            unique_together={('advertisement', 'ip_address')},
        ),
    ]
