# Generated by Django 5.2.1 on 2025-05-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicites', '0003_advertisementview_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
