# Generated by Django 5.2.1 on 2025-05-28 00:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_culture', models.CharField(choices=[('CEREALE', 'Céréale'), ('LEGUME', 'Légume'), ('FRUIT', 'Fruit'), ('TUBERCULE', 'Tubercule'), ('AUTRE', 'Autre')], max_length=20)),
                ('cycle_croissance', models.PositiveIntegerField(help_text='Durée en jours')),
                ('besoin_eau', models.PositiveIntegerField(help_text='Besoin en eau (mm/saison)')),
                ('temperature_ideale', models.CharField(help_text='Plage de température idéale', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cultures/')),
            ],
        ),
        migrations.CreateModel(
            name='PratiqueAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('saison', models.CharField(choices=[('PLUIE', 'Saison des pluies'), ('SECHE', 'Saison sèche'), ('TOUTE', 'Toute saison')], max_length=20)),
                ('avantages', models.TextField()),
                ('difficulte', models.PositiveIntegerField(help_text='Niveau de difficulté (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratiques', to='agriculture.culture')),
            ],
            options={
                'verbose_name': 'Pratique agricole',
                'verbose_name_plural': 'Pratiques agricoles',
                'ordering': ['-date_creation'],
            },
        ),
    ]
