# Generated by Django 5.2.1 on 2025-05-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
